- name: "check if spidernest db volume exists"
  command: docker volume inspect {{ SP_DB_VOLUME }}
  become: True
  register: myvolume_exists
  failed_when: false

- name: "create spidernest db volume"
  command: docker volume create --name {{ SP_DB_VOLUME }}
  become: True
  when: myvolume_exists|failed

- name: "Create spidernest directories"
  become: True
  command: |
    docker run --rm -i -v {{ SP_DB_VOLUME }}:/db {{ alpine_image }} ash -c \
      "mkdir -p /db/database /db/dblogs"

- name: "Create project dir"
  file:
    name: /tmp/spidernest
    state: directory

- name: "Copy dockerfile"
  template:
    src: docker-compose.j2
    dest: /tmp/spidernest/docker-compose.yml

- name: "Create service"
  become: True
  docker_service:
    state: present
    project_src: /tmp/spidernest

- name: "Update firewall configuration"
  include: firewall.yml
  become: True

- name: "Remove project dir"
  file:
    name: /tmp/spidernest
    state: absent
